class UserModel {
  String id;
  String name;
  String email;
  String status;
  String phone;
  String state;
  double latitude;
  double longitude;
  String role;
  String accountNumber;
  String bankName;
  String accountName;
  String paymentOption;
  String bvn;
  String nin;
  String dobImage;
  String dobImageId;
  String ninImage;
  String ninImageId;
  String driverLicenseImage;
  String driverLicenseImageId;
  bool isCompletedRegistration;
  String month;
  int year;
  List<dynamic> acceptedPackage;
  List<dynamic> payment;
  int totalRevenue;

  UserModel({
    required this.id,
    required this.name,
    required this.email,
    required this.status,
    required this.phone,
    required this.state,
    required this.latitude,
    required this.longitude,
    required this.role,
    required this.accountNumber,
    required this.bankName,
    required this.accountName,
    required this.paymentOption,
    required this.bvn,
    required this.nin,
    required this.dobImage,
    required this.dobImageId,
    required this.ninImage,
    required this.ninImageId,
    required this.driverLicenseImage,
    required this.driverLicenseImageId,
    required this.isCompletedRegistration,
    required this.month,
    required this.year,
    required this.acceptedPackage,
    required this.payment,
    required this.totalRevenue,
  });
}
